'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.4927
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class category1

    '''<summary>
    '''categoryUpdatePanel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents categoryUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''categoryGridView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents categoryGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''updateCategoryNameIsRepeatCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents updateCategoryNameIsRepeatCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''delCategoryNameCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents delCategoryNameCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''delDefaultCategoryNameCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents delDefaultCategoryNameCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''categoryAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents categoryAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''productGridView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents productGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''newCategoryTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents newCategoryTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''newCategoryTextBox_TextBoxWatermarkExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents newCategoryTextBox_TextBoxWatermarkExtender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''addCategoryButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents addCategoryButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''insertCategoryResultDialog 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents insertCategoryResultDialog As Global.DNA.UI.JQuery.Dialog

    '''<summary>
    '''newCategoryRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents newCategoryRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''newCategoryNameIsRepeatCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents newCategoryNameIsRepeatCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''newCategoryRegularExpressionValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents newCategoryRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''productAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents productAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource
End Class
