'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.3603
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class product_purchase

    '''<summary>
    '''orderGridView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents orderGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''orderAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents orderAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''orderShowDetailsView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents orderShowDetailsView As Global.System.Web.UI.WebControls.DetailsView

    '''<summary>
    '''dateErrorCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents dateErrorCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''orderShowAllAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents orderShowAllAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''orderDetailGridView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents orderDetailGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''shippingCostLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents shippingCostLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''discountLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents discountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''totalCostLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents totalCostLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''orderDetailAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents orderDetailAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''Dialog1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Dialog1 As Global.DNA.UI.JQuery.Dialog
End Class
