'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.4927
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class product_data_management

    '''<summary>
    '''insertLinkButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents insertLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''otherLinkButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents otherLinkButton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''mainMultiView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents mainMultiView As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''insertView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents insertView As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''nameTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents nameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''insertProductRequiredFieldValidator0 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents insertProductRequiredFieldValidator0 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''categoryDropDownList 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents categoryDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''categoryAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents categoryAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''insertProductRequiredFieldValidator2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents insertProductRequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''productContentFCKeditor 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents productContentFCKeditor As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''priceTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents priceTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''insertProductRequiredFieldValidator1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents insertProductRequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''priceCompareValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents priceCompareValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''saleRadioButtonList 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents saleRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''insertProductRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents insertProductRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''selectPhotoWay1RadioButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents selectPhotoWay1RadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''showImageFilenamesDropDownList 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents showImageFilenamesDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''photoCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents photoCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''selectPhotoWay2RadioButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents selectPhotoWay2RadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''photoFileUpload 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents photoFileUpload As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''selectPhotoWay3RadioButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents selectPhotoWay3RadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''showDefaultImage 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents showDefaultImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''insertProductButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents insertProductButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''productInsertCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents productInsertCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''updateAndDeleteAndQueryView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents updateAndDeleteAndQueryView As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''allProductGridView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents allProductGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''productAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents productAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''editProductDetailsView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents editProductDetailsView As Global.System.Web.UI.WebControls.DetailsView

    '''<summary>
    '''productUpdateDeleteAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents productUpdateDeleteAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''GridView1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''productMainPhotoAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents productMainPhotoAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''priceManagerPanel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents priceManagerPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''productPriceGridView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents productPriceGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''priceAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents priceAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''priceDetailsView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents priceDetailsView As Global.System.Web.UI.WebControls.DetailsView

    '''<summary>
    '''priceUpdateAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents priceUpdateAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''Dialog1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Dialog1 As Global.DNA.UI.JQuery.Dialog
End Class
