'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.4927
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class comments_to_admin

    '''<summary>
    '''defectUpdatePanel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents defectUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''defectMultiView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents defectMultiView As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''defectView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents defectView As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''contentTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents contentTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''submitButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents submitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''defectListView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents defectListView As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''defectAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents defectAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''Dialog1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Dialog1 As Global.DNA.UI.JQuery.Dialog

    '''<summary>
    '''defectUpdateProgress 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents defectUpdateProgress As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''defectUpdatePanelAnimationExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents defectUpdatePanelAnimationExtender As Global.AjaxControlToolkit.UpdatePanelAnimationExtender
End Class
