'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.4927
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class email_link

    '''<summary>
    '''emailLinkTabs 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents emailLinkTabs As Global.DNA.UI.JQuery.Tabs

    '''<summary>
    '''View0 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents View0 As Global.DNA.UI.JQuery.View

    '''<summary>
    '''s1UpdatePanel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents s1UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''setDefaultGridView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents setDefaultGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''defaultGridView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents defaultGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''View1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents View1 As Global.DNA.UI.JQuery.View

    '''<summary>
    '''s2UpdatePanel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents s2UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''newEmailTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents newEmailTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxWatermarkExtender1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TextBoxWatermarkExtender1 As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''addNewEmailButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents addNewEmailButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''newEMailRegularExpressionValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents newEMailRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''newEMailRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents newEMailRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''newEMailCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents newEMailCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''successDialog 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents successDialog As Global.DNA.UI.JQuery.Dialog

    '''<summary>
    '''addFailDialog 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents addFailDialog As Global.DNA.UI.JQuery.Dialog

    '''<summary>
    '''View2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents View2 As Global.DNA.UI.JQuery.View

    '''<summary>
    '''s3UpdatePanel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents s3UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''deleteEMailGridView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents deleteEMailGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''idEmailAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents idEmailAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''defaultIdEmailAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents defaultIdEmailAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''exceptDefaultIdEmailAccessDataSource 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents exceptDefaultIdEmailAccessDataSource As Global.System.Web.UI.WebControls.AccessDataSource
End Class
