'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.4927
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class WebForm5

    '''<summary>
    '''MainUpdatePanelAnimationExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents MainUpdatePanelAnimationExtender As Global.AjaxControlToolkit.UpdatePanelAnimationExtender

    '''<summary>
    '''MainUpdatePanel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents MainUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''StepTableLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents StepTableLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MainPanel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents MainPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MainMultiView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents MainMultiView As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''NoAuthView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents NoAuthView As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''Step1View 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Step1View As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CodeMultiView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CodeMultiView As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''CheckView 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CheckView As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''CodePlaceHolder 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CodePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''CodeTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CodeTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CodeTextbox_TextBoxWatermarkExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CodeTextbox_TextBoxWatermarkExtender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''CodeRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CodeRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CodeRequiredFieldValidator_ValidatorCalloutExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CodeRequiredFieldValidator_ValidatorCalloutExtender As Global.AjaxControlToolkit.ValidatorCalloutExtender

    '''<summary>
    '''CheckCodeButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CheckCodeButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tryCodeNoticeLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents tryCodeNoticeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''regFailCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents regFailCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''Step2View 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Step2View As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''AgreeTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents AgreeTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AgreeCheckBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents AgreeCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''AgreeCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents AgreeCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''Step3View 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Step3View As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''EMailTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents EMailTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EMailTextBox_FilteredTextBoxExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents EMailTextBox_FilteredTextBoxExtender As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''EMailTextBox_TextBoxWatermarkExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents EMailTextBox_TextBoxWatermarkExtender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''EMailRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents EMailRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''EMailRegularExpressionValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents EMailRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''EMailTextBoxCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents EMailTextBoxCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''PasswordTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents PasswordTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PasswordTextBox_PasswordStrength 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents PasswordTextBox_PasswordStrength As Global.AjaxControlToolkit.PasswordStrength

    '''<summary>
    '''PasswordHelpLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents PasswordHelpLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PasswordRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents PasswordRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PasswordTextboxRegularExpressionValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents PasswordTextboxRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ConfirmPasswordTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ConfirmPasswordTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ConfirmPasswordRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ConfirmPasswordRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ConfirmPasswordTextobxCompareValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ConfirmPasswordTextobxCompareValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''NameTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents NameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NameTextBox_TextBoxWatermarkExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents NameTextBox_TextBoxWatermarkExtender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''NameTextboxRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents NameTextboxRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NameRegularExpressionValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents NameRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''SexRadioButtonList 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents SexRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''SexRadioButtonListRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents SexRadioButtonListRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BirthdayTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents BirthdayTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BirthdayTextBox_MaskedEditExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents BirthdayTextBox_MaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''BirthdayTextbox_TextBoxWatermarkExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents BirthdayTextbox_TextBoxWatermarkExtender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''BirthdayTextBox_CalendarExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents BirthdayTextBox_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''BirthdayTextBoxRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents BirthdayTextBoxRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BirthdayTextBoxRangeValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents BirthdayTextBoxRangeValidator As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CellPhoneTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CellPhoneTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CellPhoneTextBox_TextBoxWatermarkExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CellPhoneTextBox_TextBoxWatermarkExtender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''CellPhoneTextBox_MaskedEditExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CellPhoneTextBox_MaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''CellPhoneTextBoxRegularExpressionValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CellPhoneTextBoxRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''HomePhoneTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HomePhoneTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HomePhoneTextbox_TextBoxWatermarkExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HomePhoneTextbox_TextBoxWatermarkExtender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''HomePhoneTextbox_MaskedEditExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HomePhoneTextbox_MaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''HomePhoneRegularExpressionValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HomePhoneRegularExpressionValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''IdentificationCardNumTextBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents IdentificationCardNumTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''IdentificationCardNumTextBox_TextBoxWatermarkExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents IdentificationCardNumTextBox_TextBoxWatermarkExtender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''IdentificationCardNumTextBox_MaskedEditExtender 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents IdentificationCardNumTextBox_MaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''IdentificationCardNumTextBoxRequiredFieldValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents IdentificationCardNumTextBoxRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''IdentificationCardNumTextBoxCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents IdentificationCardNumTextBoxCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''IdentificationCardNumTextBoxCheckRepeatValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents IdentificationCardNumTextBoxCheckRepeatValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''Step4View 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Step4View As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''EMailLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents EMailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PasswordLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents PasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NameLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents NameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SexLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents SexLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BirthdayLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents BirthdayLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CellPhoneLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents CellPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HomePhoneLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents HomePhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IdentificationCardNumLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents IdentificationCardNumLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ConfirmInformationCheckBox 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ConfirmInformationCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ConfirmInfoCustomValidator 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ConfirmInfoCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''Step5View 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Step5View As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''resultLabel 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents resultLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PreStepButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents PreStepButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NextStepButton 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''將移動欄位宣告從設計檔案修改為程式碼後置檔案。
    '''</remarks>
    Protected WithEvents NextStepButton As Global.System.Web.UI.WebControls.Button
End Class
